### ISSUE TITLE
fix service.fabricatorz.com urls in the code

### ISSUE THREAD

**Issue by ghost** [contributoragreements/ca-cla-chooser#2]
Ugh, comes from a server delete, needs to move service to contributoragreements.org

- [ ] find out if have access to that server
- [ ] locate where and if those services exist
- [ ] if not, then deploy them
- [ ] change urls and test on some non live server
- [ ] get working
- [ ] then move on...

**Comment by rejon** [comment]
Ok, I redeployed service.fabricatorz.com but looks like it is running on the contributoragreements.org server.org in part from what I setup years ago. 

And, looks like html2pdf deployed as heroku app: http://fab2pdf.herokuapp.com

This is only for the live site.

For the master branch of https://github.com/contributoragreements/ca-cla-chooser looks like back to service.fabricatorz.com ;)

So for now, good to stay with and then make sure everything good on the live server later.

**Comment by rejon** [comment]
The code for service.fabricatorz.com is https://github.com/Fabricatorz/service.fabricatorz.com

**Comment by christopheradams** [comment]
Helpful link: [search?q=service.fabricatorz.com&type=Code](https://github.com/Fabricatorz/ca-cla-chooser/search?q=service.fabricatorz.com&type=Code&utf8=%E2%9C%93)

**Comment by step21** [comment]
On the live site, this is replaced by http://fab2pdf.herokuapp.com
But only present in 'stable' in my repository, not master or dev branch

**Comment by rejon** [comment]
I merged all your changes to master on the new master here. Is that not
wise? Should I just go back to my original repo and blow away your changes
or are they useful?

Main thing, want to just have one master branch and move this thing forward.

Best to have those services all rolled out on contributoragreements.org

**Comment by step21** [comment]
No, that should be fine. But I just didn't merge that change before starting other work and locally it didn't really matter to me. If you find the changes useful that depends... there are probably some errors still as I often got confues with variable/id names... but one master branch should be fine.
As the vserver this runs on is enough of a mess already, I really do not want a publicly available service that processes arbitrary input running on there. That's why I moved it to heroku when service.fabricatorz shut it down.

**Comment by danielriesner** [comment]
As rejon knows I'm currently finalizing the implementation of the FSFE FLA. For now I've included http://fab2pdf.herokuapp.com/ instead of http://service.fabricatorz.com/html2pdf/. I hope this is okay? What do you guys think of going for a js html to pdf solution in the future e.g. https://github.com/MrRio/jsPDF ?

**Comment by silverhook** [comment]
Is there still stuff to do here?

**Comment by mcjsca** [comment]
I think so: https://github.com/contributoragreements/ca-cla-chooser/search?q=fabricatorz.com&unscoped_q=fabricatorz.com

**Comment by step21** [comment]
* @TODO need to have some kind of timeout on the shorturl service, its blocking when service down
* @TODO finish making u2s work on catharina's server, with apache (server down right now)

(from code)

**Comment by step21** [comment]
* @TODO FI: url shortening broken in chrome because of XHR / cross-site scripting

**Comment by step21** [comment]
```
* @TODO not working now, changed to localhost in index.html for now

$("#html2pdf-form-individual").attr("action", serviceUrl +
```

**Comment by step21** [comment]
u2s seems broken, might be because of hosting change, wrote ticket.

**Comment by step21** [comment]
fixed some links by symbolic link to /chooser from ca-cla-chooser directory

**Comment by step21** [comment]
Either done or moved to other issues. Feel free to reopen or preferrably open a more specific issue.
