### ISSUE TITLE
Fix numbering when "License obligations by us" is removed

### ISSUE THREAD

**Issue by step21** [contributoragreements/ca-cla-chooser#85]
When there is no commitment to any license, the numbering is not updated and therefore incorrect. See also https://github.com/contributoragreements/ca-cla-chooser/issues/40

**Comment by step21** [comment]
As part of this:
* test for getting numbering as one list
* testing continuous numbering (using cheerio)

**Comment by step21** [comment]
Fixed in #89 
Still needs tests.

**Comment by silverhook** [comment]
I just had an idea for an alternative solution – and please don’t kill me @step21, it’s just an idea up for discussion.

What about instead of bothering with re-numbering, we keep the numbering of the sections fixed, but write “removed” or “intentionally omitted” there?

pro:
- the numbering of sections stays consistent between different FLA/CLA variations – e.g ”§8 Term” is always §8 (and not §7 in certain cases, as now)

con:
- ugly

pro or con?:
- might cause questions as to why it was removed/omitted (potentially pro, since we probably prefer people committing to the outbound license)

@catharinamaracke, would love to hear your thought here too.

**Comment by silverhook** [comment]
Please don’t kill me №2, because in my current proposal I have changed the numbering quite a bit. Still up for debate, of course, but we have to start with something tangible :)

I just double-checked, and my re-numbering does not fix this issue (nor make it any worse really).

TBH, in descending order of my preference, I’d say:
1. the option to not have _any_ licensing commitment (Option 5) should be scratched
2. if we decide to keep that option, we should create a text explaining this situation
3. simply add `[removed]` or something similar to keep the numbering in tact

**Comment by silverhook** [comment]
Suggestion by @LeChasseur: why don’t we just get rid of the numbers in the headings and refer to the (sub)sections simply with their names.

That is probably the most elegant solution.

Unless anyone sees any specific issues with that, I’m the most in favour of that.

**Comment by silverhook** [comment]
As discussed on call with @catharinamaracke and @step21 we decided to change the numbered sections to named (sub)sections.

https://github.com/contributoragreements/ca-cla-chooser/pull/94/changes/06f863585088fbf5cd00ea1f9ec76a209151d59a fixes this issue.
